### ISSUE TITLE
DNS

### ISSUE THREAD

**Issue by tamalsaha** [tamalsaha/learn-bash#42]
- https://unix.stackexchange.com/questions/750906/how-do-i-permanently-configure-the-dns-resolution-in-ubuntu-for-all-programs-lay
- https://unix.stackexchange.com/a/442599/42136
- https://wiki.archlinux.org/title/Systemd-networkd

`/etc/netplan/*`
`/usr/lib/systemd/network/*`
`/etc/nsswitch.conf`

**Comment by tamalsaha** [comment]
- /etc/netplan/01-netcfg.yaml
- /etc/systemd/network/
- /etc/systemd/network/05-eth0.network

**Comment by tamalsaha** [comment]
```
root@localhost:~# cat /etc/netplan/01-netcfg.yaml
# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: yes
```

```
root@localhost:~# cat /etc/systemd/network/05-eth0.network
# Generated by Linode Network Helper
# Thu Aug  1 05:04:51 2024 UTC
#
# This file is automatically generated on each boot with your Linode's
# current network configuration. If you need to modify this file, please
# first disable the 'Auto-configure networking' setting within your Linode's
# configuration profile:
#  - https://cloud.linode.com/linodes/62118312/configurations
#
# For more information on Network Helper:
#  - https://www.linode.com/docs/guides/network-helper/
#
# A backup of the previous config is at /etc/systemd/network/.05-eth0.network.linode-last
# A backup of the original config is at /etc/systemd/network/.05-eth0.network.linode-orig
#
# /etc/systemd/network/05-eth0.network

[Match]
Name=eth0

[Network]
DHCP=no
DNS=139.144.192.52 139.144.192.69 139.144.192.67

Domains=members.linode.com
IPv6PrivacyExtensions=false

Gateway=172.234.129.1
Address=172.234.129.88/24
```

```
systemctl restart systemd-networkd
resolvectl status
```
